###
# Copyright (2016-2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
#"33323337-3035-584D-5136-353230345131"
---
- hosts: all
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
    # name examples: "172.18.6.15", "Encl1, bay 1"
    - server_hardware_name: "MXQ703022T, bay 1"
  tasks:
    - name: Gather facts about all Server Hardwares
      oneview_server_hardware_facts:
        config: "{{ config }}"
      delegate_to: localhost

#    - debug: var=server_hardwares


#    - name: Gather paginated, filtered and sorted facts about Server Hardware
#      oneview_server_hardware_facts:
#        config: "{{ config }}"
#        params:
#          start: 0
#          count: 4
#          sort: name:ascending
#          filter: uidState='Off'
#      delegate_to: localhost

#    - debug: msg="{{server_hardwares | map(attribute='uuid') | list }}"
#    - debug: msg="{{server_hardwares | selectattr('uuid'), '33323337-3035-584D-5136-353230345131'  |  map(attribute='name')  | list }}"

    - name: obtain name from uuid
      set_fact: hw_name="{{ item.name }}" 
      when: item.uuid is defined and item.uuid == "33323337-3035-584D-5136-353230345131"
      with_items: "{{ server_hardwares }}" 

    - name: print server name
      debug: var=hw_name
      when: hw_name is defined
