###
# Copyright (2016-2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
# Lists all the server hardware that is available
# Sets a fact containing on array with the names (string) of the servers
# A server hardware is considered available when it does not have a 
# profile applied to it.
# Usage example: ansible-playbook -i hosts playbooks/hardware_list_available.yaml
---
- hosts: all
  vars:
    - config: "{{ config_path }}"
  tasks:
    - include_tasks: ../servers_tasks/profile_list.yaml

