###
# Copyright (2016-2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
# will get a list of avaialbe servers for the given profile
# Input: server_profile_name (string): name of the profile
# Example: ansible-playbook -i hosts playbooks/get_available_server_hardware_profile.yaml --extra-vars '{"server_profile_name":"SY480 bay 1"}'
---
- hosts: all
  vars:
    config: "{{ config_path }}"
    # set the name of an existent server profile to run this example
    server_profile_name: "esx-synergyhost-04"
#    server_hardware_name: "MXQ703022T, bay 1"
    profile_template_name: "ESXi-host-profile-template 1.2"
    ps: "On"
    provisioned_nic: "ManagementNIC"
    hostname_field: "Hostname"
    post_provisioning_tasks: "../config_tasks/add_host_to_vcenter.yaml"
#    server_hostname: "myserver1"
  tasks:
    - include_tasks: ../servers_tasks/hardware_available_list.yaml
    - include_tasks: ../servers_tasks/hardware_pick_one_available.yaml
    - include_tasks: ../servers_tasks/hardware_find_by_name.yaml
    - include_tasks: ../servers_tasks/hardware_get_type_uri.yaml
    - include_tasks: ../servers_tasks/template_find_by_name.yaml
    - include_tasks: ../servers_tasks/template_get_os_custom_attributes.yaml
      # This play will complain that the profile does not exist, so will ignore the erros
    - include_tasks: ../servers_tasks/profile_find_by_name.yaml
      ignore_errors: yes
    - include_tasks: ../servers_tasks/profile_set_data_before_create.yaml
    - include_tasks: ../servers_tasks/profile_create_from_template.yaml
    - include_tasks: ../servers_tasks/profile_get_hw.yaml
    - include_tasks: ../servers_tasks/hardware_get_name_by_uuid.yaml
    - include_tasks: ../servers_tasks/hardware_get_pw.yaml
    - include_tasks: ../servers_tasks/hardware_set_pw.yaml
      when: ps is defined and ps
    - include_tasks: ../servers_tasks/profile_get_connections.yaml
    - include_tasks: ../servers_tasks/profile_inventory.yaml
    - include_tasks: ../config_tasks/wait_for_host_online.yaml

- hosts: new_servers
  tasks:
    - include_tasks: ../config_tasks/host_test.yaml
    - include_tasks: {{ post_provisioning_tasks }}
